### ISSUE TITLE
Icon Request: gmsh

### ISSUE THREAD

**Issue by tkoyama010** [rudrab/Shadow#121]
gmsh icon is missing in Ubuntu. Thank you.

**Comment by rudrab** [comment]
Hi,
Thanks for your request. In the corresponding source code, there are many icons for gmesh.
Can you please send me /usr/share/applications/gmsh*.desktop files? That will really make the process fast.

**Comment by tkoyama010** [comment]
Thank you for quick response. This is  *.desktop file and xpm file.
Please delete ".txt" from filename after you download them.
[gmsh.desktop.txt](https://github.com/rudrab/Shadow/files/1609580/gmsh.desktop.txt)
[gmsh_32x32.xpm.txt](https://github.com/rudrab/Shadow/files/1609581/gmsh_32x32.xpm.txt)

**Comment by rudrab** [comment]
Hi, 
Thanks. The icon is themed and pushed to github. Please pull it.
Also, since the icon uses an absolute path, kindly follow [this instruction](http://rudrab.github.io/Shadow/#icon-themed-but-does-not-appear).

Please consider upvoting the theme at [opendesktop](https://www.opendesktop.org/p/1012532/).

**Comment by tkoyama010** [comment]
Thank you for your support.
