### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by kugo12** [rudrab/Shadow#131]
Jetbrains Toolbox
Android Studio

**Comment by rudrab** [comment]
Hi,
Android Studio is already themed.You can not see it because https://rudrab.github.io/Shadow/#icon-themed-but-does-not-appear

Also, for jetbrain, kindly send me the corresponding `.desktop`  file, so that I know how the icon is called.

**Comment by kugo12** [comment]
>
> [Desktop Entry]
> Type=Application
> Name=JetBrains Toolbox
> Exec=/home/<username>/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox %u
> Icon=/home/<username>/.local/share/JetBrains/Toolbox/toolbox.svg
> StartupNotify=false
> Categories=Development;IDE;
> Terminal=false
> X-GNOME-Autostart-enabled=true
> StartupWMClass=jetbrains-toolbox
> MimeType=x-scheme-handler/jetbrains;
>
>

2018-06-29 12:51 GMT+02:00 rudrab <notifications@github.com>:

**Comment by rudrab** [comment]
hi,
the icon is updated, unfortunately I cant push it to github right now(the push is not working somehow). Can you download it from opendesktop (https://www.opendesktop.org/p/1012532/).

Also, you need to change your desktop entry(copy the desktop file to `~/.local/share/applications/`):

and make 
` Icon=jetbrain-toolbox
`
instead of 

` Icon=/home/<username>/.local/share/JetBrains/Toolbox/toolbox.svg
`
