### ISSUE TITLE
Icon Request: 3 more

### ISSUE THREAD

**Issue by murpholinox** [rudrab/Shadow#77]
1. remarkable https://remarkableapp.github.io/linux.html
[Desktop Entry]
Name=Remarkable
Comment=A free, fully featured markdown editor for Linux.
Categories=GNOME;Utility;
Exec=/usr/bin/remarkable %f
Icon=remarkable
Terminal=false
Type=Application

2. nvidia settings www.nvidia.com
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=NVIDIA X Server Settings
Comment=Configure NVIDIA X Server Settings
Exec=optirun -b none nvidia-settings -c :8
Icon=/usr/share/doc/NVIDIA_GLX-1.0/nvidia-settings.png
Categories=Application;Settings;

3. aymptote http://asymptote.sourceforge.net/
[Desktop Entry]
Encoding=UTF-8
Exec=xasy
Icon=/usr/share/pixmaps/asy.gif
Terminal=false
Name=Asymptote
GenericName=xasy
Comment=GUI tool for using Asymptote vector graphics
Type=Application
Categories=Application;Graphics;
StartupNotify=true
X-Desktop-File-Install-Version=0.22

**Comment by rudrab** [comment]
Hi,
I have added the icons, and nvidia is already in the repo. 
The problem is `nvidia` and `asymptot` is using absolute path, so you can understand that it will never get the themed icons (which you probably place in your `~/home` folder). 

You have 2 options:

1) Copy them in your `~/.local/share/applications` and change the icon path.
2)You can also edit them in place, `/local/share/applications` as root. But the problem with this approach is, anything you edit will be overwritten.

You will probably like to have something like this:

nvidia settings www.nvidia.com
```
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=NVIDIA X Server Settings
Comment=Configure NVIDIA X Server Settings
Exec=optirun -b none nvidia-settings -c :8
Icon=nvidia-settings
Categories=Application;Settings;
```


aymptote http://asymptote.sourceforge.net/
```
[Desktop Entry]
Encoding=UTF-8
Exec=xasy
Icon=asy
Terminal=false
Name=Asymptote
GenericName=xasy
Comment=GUI tool for using Asymptote vector graphics
Type=Application
Categories=Application;Graphics;
StartupNotify=true
X-Desktop-File-Install-Version=0.22
```

I hope it will work fine then.
Please let me know if you have any problem.
